# register services in combination with the CMF
services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

    # example customer save handler config
    appbundle.cmf.customer_save_handler.normalize_zip:
       class: CustomerManagementFrameworkBundle\CustomerSaveHandler\NormalizeZip
       tags: [cmf.customer_save_handler]

    # example segment builder config
    appbundle.cmf.segment_builder.state:
         class: CustomerManagementFrameworkBundle\SegmentBuilder\StateSegmentBuilder
         tags: [cmf.segment_builder]

    appbundle.cmf.segment_builder.gender:
         class: CustomerManagementFrameworkBundle\SegmentBuilder\GenderSegmentBuilder
         tags: [cmf.segment_builder]

    appbundle.cmf.segment_builder.productCategory:
         class: AppBundle\CustomerManagementFramework\SegmentBuilder\ProductCategorySegmentBuilder
         tags: [cmf.segment_builder]

    # authentication login listener for updating e-commerce framework environment after login
    AppBundle\EventListener\AuthenticationLoginListener:
        arguments:
            $httpUtils: '@security.http_utils'

    # authentication login listener for updating e-commerce framework environment after logout
    AppBundle\EventListener\AuthenticationLogoutListener:
        arguments:
            $httpUtils: '@security.http_utils'

    # services for forms
    AppBundle\Form\RegistrationFormHandler: ~
    AppBundle\Form\DeliveryAddressFormType: ~
