app:
    resource: "@AppBundle/Controller/"
    type:     annotation


# route for login with SSO provider like google, twitter, etc.
app_auth_oauth_login:
    path: /auth/oauth/login/{service}
    defaults:
        _controller: HWIOAuthBundle:Connect:redirectToService

# virtual routes for oauth resource owners
app_auth_oauth_check_google:
    path: /auth/oauth/check/google
app_auth_oauth_check_twitter:
    path: /auth/oauth/check/twitter
